
package co.gov.colpensiones.services.consultaestadotramite;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-07-20T12:05:07.778-05:00
 * Generated source version: 3.2.6
 *
 */

public class ConsultaEstadoTramite_ConsultaEstadoTramitePort_Server{

    protected ConsultaEstadoTramite_ConsultaEstadoTramitePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ConsultaEstadoTramitePortImpl();
        String address = " http://10.130.70.126:13040/Colpensiones/Services/ConsultaEstadoTramite";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ConsultaEstadoTramite_ConsultaEstadoTramitePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
