package co.gov.colpensiones.services.consultaestadotramite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-07-20T12:05:07.762-05:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://www.colpensiones.gov.co/services/ConsultaEstadoTramite", name = "ConsultaEstadoTramite")
@XmlSeeAlso({org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class, co.gov.colpensiones.portal.common.webservices.wsse.requestsystem.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class, co.gov.colpensiones.schemas.consultaestadotramite.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConsultaEstadoTramite {

    @WebMethod(operationName = "EstadoTramite", action = "EstadoTramite")
    @WebResult(name = "ConsultaEstadoTramiteResponse", targetNamespace = "http://www.colpensiones.gov.co/schemas/ConsultaEstadoTramite", partName = "parameters")
    public co.gov.colpensiones.schemas.consultaestadotramite.ConsultaEstadoTramiteResponse estadoTramite(
        @WebParam(partName = "parameters", name = "ConsultaEstadoTramiteRequest", targetNamespace = "http://www.colpensiones.gov.co/schemas/ConsultaEstadoTramite")
        co.gov.colpensiones.schemas.consultaestadotramite.ConsultaEstadoTramiteRequest parameters
    );
}
