
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package co.gov.colpensiones.services.consultaestadotramite;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-07-20T12:05:07.723-05:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "ConsultaEstadoTramite",
                      portName = "ConsultaEstadoTramitePort",
                      targetNamespace = "http://www.colpensiones.gov.co/services/ConsultaEstadoTramite",
                      wsdlLocation = "file:/C:/Users/john/AppData/Local/Temp/tempdir2250200112895305352.tmp/SOAPServiceBinding_1.wsdl",
                      endpointInterface = "co.gov.colpensiones.services.consultaestadotramite.ConsultaEstadoTramite")

public class ConsultaEstadoTramitePortImpl implements ConsultaEstadoTramite {

    private static final Logger LOG = Logger.getLogger(ConsultaEstadoTramitePortImpl.class.getName());

    /* (non-Javadoc)
     * @see co.gov.colpensiones.services.consultaestadotramite.ConsultaEstadoTramite#estadoTramite(co.gov.colpensiones.schemas.consultaestadotramite.ConsultaEstadoTramiteRequest parameters)*
     */
    public co.gov.colpensiones.schemas.consultaestadotramite.ConsultaEstadoTramiteResponse estadoTramite(co.gov.colpensiones.schemas.consultaestadotramite.ConsultaEstadoTramiteRequest parameters) {
        LOG.info("Executing operation estadoTramite");
        System.out.println(parameters);
        try {
            co.gov.colpensiones.schemas.consultaestadotramite.ConsultaEstadoTramiteResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
