package co.gov.colpensiones.services.consultaestadotramite;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-07-20T12:05:07.787-05:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "ConsultaEstadoTramite",
                  wsdlLocation = "file:/C:/certificados/SOAPServiceBinding.wsdl",
                  targetNamespace = "http://www.colpensiones.gov.co/services/ConsultaEstadoTramite")
public class ConsultaEstadoTramite_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.colpensiones.gov.co/services/ConsultaEstadoTramite", "ConsultaEstadoTramite");
    public final static QName ConsultaEstadoTramitePort = new QName("http://www.colpensiones.gov.co/services/ConsultaEstadoTramite", "ConsultaEstadoTramitePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/certificados/SOAPServiceBinding.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaEstadoTramite_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/john/AppData/Local/Temp/tempdir2250200112895305352.tmp/SOAPServiceBinding_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaEstadoTramite_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaEstadoTramite_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaEstadoTramite_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConsultaEstadoTramite_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultaEstadoTramite_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultaEstadoTramite_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConsultaEstadoTramite
     */
    @WebEndpoint(name = "ConsultaEstadoTramitePort")
    public ConsultaEstadoTramite getConsultaEstadoTramitePort() {
        return super.getPort(ConsultaEstadoTramitePort, ConsultaEstadoTramite.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaEstadoTramite
     */
    @WebEndpoint(name = "ConsultaEstadoTramitePort")
    public ConsultaEstadoTramite getConsultaEstadoTramitePort(WebServiceFeature... features) {
        return super.getPort(ConsultaEstadoTramitePort, ConsultaEstadoTramite.class, features);
    }

}
